### ISSUE TITLE
Demo won't run

### ISSUE THREAD

**Issue by davidgs** [userfront/react-example#3]
```
$ nom start
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/davidgs/github.com/react-example/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/davidgs/github.com/react-example/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/davidgs/github.com/react-example/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/davidgs/github.com/react-example/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/davidgs/github.com/react-example/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/davidgs/github.com/react-example/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/davidgs/github.com/react-example/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/davidgs/github.com/react-example/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/davidgs/github.com/react-example/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/davidgs/github.com/react-example/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/davidgs/github.com/react-example/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/davidgs/github.com/react-example/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/davidgs/github.com/react-example/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/davidgs/github.com/react-example/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/davidgs/github.com/react-example/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/davidgs/github.com/react-example/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/davidgs/github.com/react-example/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.5.0
```

**Comment by isanchez-userfront** [comment]
Hey @davidgs although our [toolkit](https://github.com/userfront/toolkit) (https://userfront.com/dashboard/toolkit) is compatible with newer versions of Node, this example requires version 16. 

![Screenshot 2024-01-16 at 8 03 48 PM](https://github.com/userfront/react-example/assets/147533431/8a0ac458-711d-46ce-b5d9-6c65a8eeec54)

I recommend using [nvm](https://github.com/nvm-sh/nvm). Let us know if there's anything more we can do to help.

**Comment by isanchez-userfront** [comment]
Feel free to [contact us](https://userfront.com/contact) for further assistance anytime. I'll be closing this issue for now. Thank you!
